### PR TITLE
remove snowflake channel, bump up build number

### PR DESCRIPTION
**Pull request by M-Waszkiewicz-Anaconda**
remove snowflake channel, bump up build number in order to push it to defaults

### CODE REVIEW

**Review by skupr-anaconda — APPROVED** [review]

**Comment by JeanChristopheMorinPerso** [comment]
Why do you remove the snowflake channel? It's a dependency of dbt which is only on snowflake.

**Comment by M-Waszkiewicz-Anaconda** [comment]
> Why do you remove the snowflake channel? It's a dependency of dbt which is only on snowflake.

yes, but dbt-extractor 0.4.1 was already on defaults, so if we do updates it goes to defaults

**Review by lorepirri — APPROVED** [review]
if version `0.5` is new in `defaults`, do we need to bump the build number? or is it because SF will detect a newer version and pick that one?

**Comment by M-Waszkiewicz-Anaconda** [comment]
> if version `0.5` is new in `defaults`, do we need to bump the build number? or is it because SF will detect a newer version and pick that one?

yes, we bumping  to shadow the one from snowflake channel

**Pull request merged**
